#pragma once
#define ERROR 1
#define INIT_ERROR 2
#define INIT_WINDOW_ERROR 3
#define INIT_RENDERER_ERROR 4
#define SURFACE_ERROR 5
#define TEXTURE_ERROR 6
#define LOAD_IMAGE_ERROR 7
#define MEMORY_ALLOCATION_ERROR 8
#define PIXEL_READ_ERROR 9
#define PIXEL_TO_COLOR_CONVERSION_ERROR 10
#define EMPTY_MAP_ERROR 11
#define MALFORMED_MAP 12
#define SURFACE_LOCK_ERROR 13